### ISSUE TITLE
INFO out of a buffalo folder

### ISSUE THREAD

**Issue by hubyhuby** [gobuffalo/buffalo-pop#12]
This is a small display bug.
When outside of a buffalo folder using 0.14 "buffalo pop" gives an error, saying you have to install it....
Inside a project folder it works like charm.

The behaviour outside should simply be to display the regular info about the plugin.

With 0.14.3 "buffalo pop" command displays :

ERRO[0000] Pop support has been moved to the https://github.com/gobuffalo/buffalo-pop plugin.

!! PLEASE READ PLUGIN DOCUMENTATION - https://gobuffalo.io/en/docs/plugins

Buffalo Plugins Installation*:

	$ buffalo plugins install github.com/gobuffalo/buffalo-pop

* Requires https://github.com/gobuffalo/buffalo-plugins installed.

**Comment by jcarley** [comment]
I'm having a similar issue with  Buffalo 0.14.6.  I have buffalo-pop specified in my `config/buffalo-plugins.toml` file.  It appears to install it.  I can run `buffalo-pop` just fine.  But I'm not able to get any buffalo cli integration to work.  We use to be able to run `buffalo pop` commands.  Even fails inside a buffalo project folder.  This also means that `buffalo setup` is failing.  This was discovered this week because we are on-boarding new folks.

**Comment by qwrobins** [comment]
@hubyhuby  @jcarley I occasionally run into this on different OS's. Using go get usually fixes everything up for me as it seems to do a better job of getting everything into go/bin in those cases.

```
go get -u -v github.com/gobuffalo/buffalo/buffalo
```

**Comment by hubyhuby** [comment]
Thanks Robin,
My gobin seems to have a problem, you are right   :    
 $GOBIN
bash: /usr/lib/go/bin/ : est un dossier
But buffalo is in the path : /usr/local/bin
so I have plugins there and buffalo in a different folder !
I think we will close this issue if others in this thread have aswell a $GOBIN issue ...

**Comment by qwrobins** [comment]
No worries @hubyhuby. Just for clarification, when I say go/bin, I mean the bin directory in your $GOPATH. So, if you have /Users/hubyhuby/go as your $GOPATH, then I would make sure to add /Users/hubyhuby/go/bin to your path variable so it will pick up the buffalo binaries that get installed there. The main buffalo binary can remain in /usr/local/bin. I wouldn't try and move any of the plugin binaries to /usr/local/bin unless you absolutely need to as that could end up causing issues for you later on.

**Comment by sio4** [comment]
answered, closing.
